.class public abstract Lge/a$a;
.super Ljava/lang/Object;
.source "r8-map-id-6fe49df57dd29ad5bed73b56f6f9b5413638df6511bd2c79e70d3c2ded0ad3ec"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lge/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Lge/a;I)[Ljava/lang/Object;
    .locals 0

    .line 1
    new-instance p0, Lwc/p;

    .line 2
    .line 3
    const-string p1, "Generated by Android Extensions automatically"

    .line 4
    .line 5
    invoke-direct {p0, p1}, Lwc/p;-><init>(Ljava/lang/String;)V

    .line 6
    .line 7
    .line 8
    throw p0
.end method
